" Set 'nocompatible' to ward off unexpected things that your distro might
" have made, as well as sanely reset options when re-sourcing .vimrc
set nocompatible

" Allows vim to manage multiple buffers better. Current buffer can
" be put to the background without writing to disk. Undo history is
" preserved.
set hidden

" Keeps more than the default 20 commands and search patterns
set history=1000

" Better command completion that shows you options rather than just
" going to the first command
set wildmenu
" Makes autocomplete act like shell: only goes up to point of ambiguity while
" still showing all options
set wildmode=list:longest

" These two, when set together make searches containing capital letters
" case sensitive
set ignorecase
set smartcase

" Makes vim set the window's title properly based on the file
" rather than inheriting the terminal's title
set title

" Keeps the cursor and some lines below it in view
set scrolloff=2

" Files changed on the system are automatically reloaded
set autoread

" Ignore compiled files
set wildignore=*.o,*~,*.pyc,*.out

" Always show current position
set ruler

" Height of command bar
set cmdheight=2

" A buffer becomes hidden when it is abandoned
set hid

" Configure backspace so it acts as it should act
set backspace=eol,start,indent
set whichwrap+=<,>,h,l

" Don't repeat comment leaders
au FileType * setlocal formatoptions-=c formatoptions-=o formatoptions-=r

" Smart way to move between windows
map <C-j> <C-W>j
map <C-k> <C-W>k
map <C-h> <C-W>h
map <C-l> <C-W>l

" Makes dealing with word wrap easier
noremap j gj
noremap k gk

" In many terminal emulators the mouse works just file, thus enable it
if has('mouse')
  set mouse=a
endif

" Makes search act like most modern browsers (immidiately finds)
set incsearch

" Don't redraw while executing macros (performance)
set lazyredraw

" Turn magic regular expressions on
set magic

" Show matching brackets
set showmatch
" How many tenths of a second to blink when matching brackets
set mat=2

" No annoying sound on errors
set noerrorbells
set novisualbell
set t_vb=
set tm=500

" Don't enable folding
set nofoldenable

" Add a bit of extra margin to the left
set foldcolumn=2

" Make it so that files aren't folded when loaded initially
set foldlevelstart=20

" Enable syntax highlighting
syntax enable

" Enable colorscheme
colorscheme desert

" Set extra options when running in GUI mode
if has("gui_running")
    set guioptions-=T
    set guioptions-=e
    set t_Co=256
    set guitablabel=%M\ %t
endif

" Set utf8 as standard encoding and en_US as the standard language
set encoding=utf8

" Use Unix as the standard file type
set ffs=unix,dos,mac

" Use spaces instead of tabs
set expandtab

" Be smart when using tabs
set smarttab

" Stop auto indentation of # character
set cindent
set cinkeys-=0#
set indentkeys-=0#

" 1 tab == 4 spaces
set shiftwidth=4
set tabstop=4
set softtabstop=4

" Linebreak on 500 characters
set lbr
set tw=500

" Auto indent
set ai
" Smart indent
set si
" Wrap lines
" set wrap

" Display line numbers
set number

" automatically change window's cwd to file's dir
set autochdir

" Forces vsplit to split to the right instead of the left
set splitright
" Forces split to split below instead of above
set splitbelow

" Fix problem with all indents before comment # being removed
autocmd BufRead *.py inoremap # X<c-h>#<space>

" Make vim commands appear so you can see which command you're typing
set showcmd

" For toggling paste mode when pasting large amounts of preformatted text
set pastetoggle=<F10>

" Stop warning about existing swap files
set shortmess+=A
